apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-master
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
    role: master
    tier: backend
spec:
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: 6379
  selector:
    app: {{ .Chart.Name }}
    role: master
    tier: backend