apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-master
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        role: master
        tier: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-master
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: {{ .Values.service.containerPort }}